sonar.projectKey=sharmaankita3387_team25_2AA4_Assignments_2026W
sonar.organization=sharmaankita3387

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=team25_2AA4_Assignments_2026W
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file
sonar.sources=Assignment2/Task3/src
sonar.java.binaries=Assignment2/Task3/out/production/Task3
sonar.java.source=17

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Coverage report
sonar.coverage.jacoco.xmlReportPaths=coverage/jacoco.xml
