sonar.projectKey=sharmaankita3387_team25_2AA4_Assignments_2026W
sonar.organization=sharmaankita3387

sonar.projectName=team25_2AA4_Assignments_2026W
sonar.projectVersion=1.0

sonar.sources=Assignment2/Task3/src
sonar.java.binaries=Assignment2/Task3/out/production/Task3

sonar.sourceEncoding=UTF-8
sonar.java.source=17

# Tell Sonar where the coverage file is
sonar.coverage.jacoco.xmlReportPaths=coverage/jacoco.xml
