// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1;

/************************************************************/
/**
 * 
 */
public class Agent {
	/**
	 * 
	 */
	protected int victoryPoints;
	/**
	 * 
	 */
	protected Resources[] hand;
	/**
	 * 
	 */
	protected String name;

	/**
	 * 
	 * @param resource 
	 */
	public void addResource(Resources resource) {
	}

	/**
	 * 
	 * @param resource 
	 */
	public void removeResource(Resources resource) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}

	/**
	 * 
	 * @return 
	 */
	public String getName() {
	}

	/**
	 * 
	 * @param victoryPoints 
	 * @param name 
	 */
	public void Agent(int victoryPoints, String name) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getHandSize() {
	}

	/**
	 * 
	 * @return 
	 */
	public Resources getrandomResourceFromHand() {
	}

	/**
	 * 
	 * @param player 
	 * @param resource 
	 */
	public void tradeResource(Agent player, Resources resource) {
	}
}
