// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Edge[] edges;
	/**
	 * 
	 */
	private Node[] nodes;
	/**
	 * 
	 */
	private Tile[] tiles;

	/**
	 * 
	 * @param index 
	 * @return 
	 */
	public Tile getTile(int index) {
	}

	/**
	 * 
	 * @param index 
	 * @return 
	 */
	public Edge getEdge(int index) {
	}

	/**
	 * 
	 * @param index 
	 * @return 
	 */
	public Node getNode(int[] index) {
	}

	/**
	 * 
	 * @param tiles 
	 * @param edges 
	 * @param nodes 
	 */
	public void Board(Tile[] tiles, Edge[] edges, Node[] nodes) {
	}

	/**
	 * 
	 * @param node 
	 * @param building 
	 */
	public void getBuildingAtNode(Node node, Building building) {
	}

	/**
	 * 
	 * @return 
	 * @return 
	 */
	public Edge getRoadAtEdge() {
	}

	/**
	 * 
	 * @param node 
	 * @param settlement 
	 */
	public void placeSettlement(Node node, Building settlement) {
	}

	/**
	 * 
	 * @param node 
	 * @param city 
	 * @param agent 
	 */
	public void placeCity(Node node, Building city, Agent agent) {
	}

	/**
	 * 
	 */
	public void getEdgeRoads() {
	}

	/**
	 * 
	 * @return 
	 */
	public Tile[] getTiles() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node[] getNodes() {
	}
}
