// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1;

/************************************************************/
/**
 * 
 */
public abstract class Building {
	/**
	 * 
	 */
	private Agent owner;
	/**
	 * 
	 */
	private int victoryPoint;

	/**
	 * 
	 * @param resource 
	 * @return 
	 */
	public abstract boolean resourcePayment(Resources[] resource);

	/**
	 * 
	 * @return 
	 */
	public Agent getAgent() {
	}

	/**
	 * 
	 * @param owner 
	 */
	public void Building(Agent owner) {
	}

	/**
	 * 
	 * @param int 
	 */
	public void getVictoryPoint(int int) {
	}
}
