// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1;

/************************************************************/
/**
 * 
 */
public class City extends Building {
	/**
	 * 
	 */
	private int resourceMultiplier;
	/**
	 * 
	 */
	private Node node;

	/**
	 * 
	 * @param resources 
	 * @return 
	 */
	public boolean resourcePayment(Resources[] resources) {
	}

	/**
	 * 
	 * @param owner 
	 * @param node 
	 */
	public void City(Agent owner, Node node) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getResourceMultiplier() {
	}
}
