// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1;

/************************************************************/
/**
 * 
 */
public class GamePlay {
	/**
	 * 
	 */
	private int turnNumber;
	/**
	 * 
	 */
	private int roundNumber;
	/**
	 * 
	 */
	private Agent[] agents;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private Dice dice;
	/**
	 * 
	 */
	private int maxRounds;

	/**
	 * 
	 * @return 
	 */
	public int getTurnNumber() {
	}

	/**
	 * 
	 * @param agents 
	 * @param board 
	 * @param dice 
	 * @param maxRounds 
	 */
	public void GamePlay(Agent[] agents, Board board, Dice dice, int maxRounds) {
	}

	/**
	 * 
	 */
	public void runSumulation() {
	}

	/**
	 * 
	 * @param agent 
	 */
	private void executeTurn(Agent agent) {
	}

	/**
	 * 
	 */
	private void distributeResources() {
	}

	/**
	 * 
	 * @param agent 
	 */
	private void performRandomBuildAction(Agent agent) {
	}

	/**
	 * 
	 * @param agent 
	 * @param node 
	 * @return 
	 */
	private boolean canPlaceSettlement(Agent agent, Node node) {
	}

	/**
	 * 
	 * @param agent 
	 * @param node 
	 * @return 
	 */
	private boolean canPlaceCity(Agent agent, Node node) {
	}

	/**
	 * 
	 */
	private void handleSevenRoll() {
	}

	/**
	 * 
	 */
	public void printRoundSummary() {
	}

	/**
	 * 
	 * @param agent 
	 * @param edge 
	 * @return 
	 */
	public String placeRoad(Agent agent, Edge edge) {
	}
}
