// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1;

/************************************************************/
/**
 * 
 */
public class HumanPlayer {
	/**
	 * 
	 */
	public Agent agent;

	/**
	 * 
	 */
	public void playerMove() {
	}
}
