// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1;

/************************************************************/
/**
 * 
 */
public class MapSetup {
	/**
	 * 
	 */
	private int[] TILE_NODES;
	/**
	 * 
	 */
	private int[] TILE_NUMBERS;

	/**
	 * 
	 * @return 
	 */
	public Board createBoard() {
	}
}
