// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1;

/************************************************************/
/**
 * 
 */
public class MultiDice {
	/**
	 * 
	 */
	private Dice[] diceList;

	/**
	 * 
	 * @param d 
	 */
	public void addDice(Dice d) {
	}
}
