// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1;

/************************************************************/
/**
 * 
 */
public class RegularDice {
	/**
	 * 
	 */
	private int sides;

	/**
	 * 
	 * @param sides 
	 */
	public void RegularDice(int sides) {
	}
}
