// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1;

/************************************************************/
/**
 * 
 */
public class Road extends Building {
	/**
	 * 
	 */
	private Edge edge;

	/**
	 * 
	 * @param resources 
	 * @return 
	 */
	public boolean resourcePayment(Resources[] resources) {
	}

	/**
	 * 
	 * @param owner 
	 * @param edge 
	 */
	public void Road(Agent owner, Edge edge) {
	}
}
