// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1;

/************************************************************/
/**
 * 
 */
public class Robber {
	/**
	 * 
	 * @param t1 
	 * @return 
	 */
	public boolean sameTile(Tile t1) {
	}
}
