// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private Resources resource;
	/**
	 * 
	 */
	private int rollValue;
	/**
	 * 
	 */
	private int tilePosition;
	/**
	 * 
	 */
	private Edge[] edges;

	/**
	 * 
	 * @param resource 
	 * @param rollValue 
	 * @param tilePosition 
	 * @param edges 
	 */
	public void Tile(Resources resource, int rollValue, int tilePosition, Edge[] edges) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getRollValue() {
	}

	/**
	 * 
	 * @param resource 
	 */
	public void getResource(Resources resource) {
	}
}
