name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          
      - name: Run Tests with Coverage
        run: |
          mkdir -p coverage
          java -javaagent:jacoco/lib/jacocoagent.jar=destfile=jacoco.exec -cp "Assignment2/Task3/out/production/Task3:libs/*" org.junit.runner.JUnitCore CommandParserTest HumanAgentTest RobberTest


      - name: Compile Source
        run: |
          mkdir -p Assignment2/Task3/out/production/Task3
          javac -d Assignment2/Task3/out/production/Task3 $(find Assignment2/Task3/src -name "*.java")

      - name: Download JaCoCo
        run: |
          curl -L https://repo1.maven.org/maven2/org/jacoco/jacoco/0.8.11/jacoco-0.8.11.zip -o jacoco.zip
          unzip jacoco.zip -d jacoco
          
      - name: Run Tests with Coverage
        run: |
          mkdir -p coverage
          java -javaagent:jacoco/jacoco-0.8.11/lib/jacocoagent.jar=destfile=jacoco.exec -cp "Assignment2/Task3/out/production/Task3:libs/*" org.junit.runner.JUnitCore CommandParserTest HumanAgentTest RobberTest
          
      - name: Generate Coverage XML
        run: |
          java -jar jacoco/jacoco-0.8.11/lib/jacococli.jar report jacoco.exec \
          --classfiles Assignment2/Task3/out/production/Task3 \
          --sourcefiles Assignment2/Task3/src \
          --xml coverage/jacoco.xml

     

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
